[package]
name = "joplin-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
eframe = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
rfd = "0.15.0"
dirs = "5.0.1"
indoc = "2.0.5"